/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    Acx.h

Abstract:

    Main header file for Audio Class eXtension client.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _ACX_H_
#define _ACX_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START




typedef VOID (*ACXFUNC) (VOID);
extern ACXFUNC AcxFunctions[];

#include "AcxTypes.h"
#include "AcxGlobals.h"
#include "AcxFuncEnum.h"
#include "AcxMisc.h"
#include "AcxDriver.h"
#include "AcxDevice.h"
#include "AcxRequest.h"
#include "AcxEvents.h"
#include "AcxPin.h"
#include "AcxCircuit.h"
#include "AcxElements.h"
#include "AcxDataFormat.h"
#include "AcxStreams.h"
#include "AcxTargets.h"
#include "AcxManager.h"






WDF_EXTERN_C_END

#endif // _ACX_H_

