/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmUcsiCx.h

Abstract:

    Main header file for UCM (USB Connector Manager) UCSI (USB Type-C Connector Software Interface) class
    extension client.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCMUCSICX_H_
#define _UCMUCSICX_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



typedef VOID (*UCMUCSIFUNC) (VOID);
extern UCMUCSIFUNC UcmucsiFunctions[];

#include "UcmUcsiGlobals.h"
#include "UcmUcsiFuncEnum.h"
#include "UcmUcsiDevice.h"
#include "UcmUcsiSpec.h"
#include "UcmUcsiPpm.h"
#include "UcmUcsiPpmRequests.h"





WDF_EXTERN_C_END

#endif // _UCMUCSICX_H_

