/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmUcsiDevice.h

Abstract:

    Methods, callbacks, and structs for a UCM-UCSI device.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCMUCSIDEVICE_H_
#define _UCMUCSIDEVICE_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START





typedef struct _UCMUCSI_DEVICE_CONFIG
{
    ULONG Size;
} UCMUCSI_DEVICE_CONFIG, *PUCMUCSI_DEVICE_CONFIG;

VOID
FORCEINLINE
UCMUCSI_DEVICE_CONFIG_INIT (
    _Out_ PUCMUCSI_DEVICE_CONFIG Config
    )
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
}

//
// UCMUCSI Function: UcmUcsiDeviceInitInitialize
//
typedef
_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
WDFAPI
NTSTATUS
(*PFN_UCMUCSIDEVICEINITINITIALIZE)(
    _In_
    PUCMUCSI_DRIVER_GLOBALS DriverGlobals,
    _In_
    PWDFDEVICE_INIT DeviceInit
    );

_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
FORCEINLINE
UcmUcsiDeviceInitInitialize(
    _In_
    PWDFDEVICE_INIT DeviceInit
    )
{
    return ((PFN_UCMUCSIDEVICEINITINITIALIZE) UcmucsiFunctions[UcmUcsiDeviceInitInitializeTableIndex])(UcmucsiDriverGlobals, DeviceInit);
}

//
// UCMUCSI Function: UcmUcsiDeviceInitialize
//
typedef
_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
WDFAPI
NTSTATUS
(*PFN_UCMUCSIDEVICEINITIALIZE)(
    _In_
    PUCMUCSI_DRIVER_GLOBALS DriverGlobals,
    _In_
    WDFDEVICE WdfDevice,
    _In_
    PUCMUCSI_DEVICE_CONFIG Config
    );

_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
FORCEINLINE
UcmUcsiDeviceInitialize(
    _In_
    WDFDEVICE WdfDevice,
    _In_
    PUCMUCSI_DEVICE_CONFIG Config
    )
{
    return ((PFN_UCMUCSIDEVICEINITIALIZE) UcmucsiFunctions[UcmUcsiDeviceInitializeTableIndex])(UcmucsiDriverGlobals, WdfDevice, Config);
}



WDF_EXTERN_C_END

#endif // _UCMUCSIDEVICE_H_

