/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmUcsiPpmRequests.h

Abstract:

    UCM-UCSI Platform Policy Manager hardware request definitions.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCMUCSIPPMREQUESTS_H_
#define _UCMUCSIPPMREQUESTS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



// Note: These IOCTL numbers are subject to change in the future.

#define IOCTL_UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK \
    CTL_CODE(FILE_DEVICE_UCMUCSI, \
             0x0, \
             METHOD_BUFFERED, \
             FILE_WRITE_ACCESS)

#define IOCTL_UCMUCSI_PPM_GET_UCSI_DATA_BLOCK \
    CTL_CODE(FILE_DEVICE_UCMUCSI, \
             0x1, \
             METHOD_BUFFERED, \
             FILE_READ_ACCESS)


// in WPP.
typedef enum _UCMUCSI_PPM_IOCTL {
    _IOCTL_UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK = IOCTL_UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK,
    _IOCTL_UCMUCSI_PPM_GET_UCSI_DATA_BLOCK = IOCTL_UCMUCSI_PPM_GET_UCSI_DATA_BLOCK,
} UCMUCSI_PPM_IOCTL;



#pragma warning(push)
#pragma warning(disable:4201) // nonstandard extension used : nameless struct/union
#include <pshpack1.h>

//
// IOCTL_UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK
//
// In Buffer Type: UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK_IN_PARAMS
//

typedef struct _UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK_IN_PARAMS
{
    UCMUCSIPPM PpmObject;
    UCSI_DATA_BLOCK UcmUcsiDataBlock;
} UCMUCSI_PPM_SEND_UCSI_DATA_BLOCK_IN_PARAMS, *PUCMUCSI_PPM_SEND_UCSI_DATA_BLOCK_IN_PARAMS;

//
// IOCTL_UCMUCSI_PPM_GET_UCSI_DATA_BLOCK
//
// In Buffer Type: UCMUCSI_PPM_GET_UCSI_DATA_BLOCK_IN_PARAMS
// Out Buffer Type: UCMUCSI_PPM_GET_UCSI_DATA_BLOCK_OUT_PARAMS
//

typedef struct _UCMUCSI_PPM_GET_UCSI_DATA_BLOCK_IN_PARAMS
{
    UCMUCSIPPM PpmObject;
} UCMUCSI_PPM_GET_UCSI_DATA_BLOCK_IN_PARAMS, *PUCMUCSI_PPM_GET_UCSI_DATA_BLOCK_IN_PARAMS;

typedef struct _UCMUCSI_PPM_GET_UCSI_DATA_BLOCK_OUT_PARAMS
{
    UCSI_DATA_BLOCK UcmUcsiDataBlock;
} UCMUCSI_PPM_GET_UCSI_DATA_BLOCK_OUT_PARAMS, *PUCMUCSI_PPM_GET_UCSI_DATA_BLOCK_OUT_PARAMS;


#include <poppack.h>
#pragma warning(pop)

WDF_EXTERN_C_END

#endif // _UCMUCSIPPMREQUESTS_H_

