/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

_WdfVersionBuild_

Module Name: UcmucsiTraceEnums.h

Abstract:
    Generated trace enums

Environment:
    kernel mode only

--*/

#ifndef _UCMUCSITRACEENUMS_H_
#define _UCMUCSITRACEENUMS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START

// begin_wpp config
// CUSTOM_TYPE(UCMUCSI_PPM_IOCTL, ItemEnum(_UCMUCSI_PPM_IOCTL));
// CUSTOM_TYPE(UCSI_COMMAND, ItemEnum(_UCSI_COMMAND));
// CUSTOM_TYPE(UCSI_USB_OPERATION_MODE, ItemEnum(_UCSI_USB_OPERATION_MODE));
// CUSTOM_TYPE(UCSI_USB_OPERATION_ROLE, ItemEnum(_UCSI_USB_OPERATION_ROLE));
// CUSTOM_TYPE(UCSI_POWER_DIRECTION_MODE, ItemEnum(_UCSI_POWER_DIRECTION_MODE));
// CUSTOM_TYPE(UCSI_POWER_DIRECTION_ROLE, ItemEnum(_UCSI_POWER_DIRECTION_ROLE));
// CUSTOM_TYPE(UCSI_GET_ALTERNATE_MODES_RECIPIENT, ItemEnum(_UCSI_GET_ALTERNATE_MODES_RECIPIENT));
// CUSTOM_TYPE(UCSI_GET_PDOS_TYPE, ItemEnum(_UCSI_GET_PDOS_TYPE));
// CUSTOM_TYPE(UCSI_GET_PDOS_SOURCE_CAPABILITIES_TYPE, ItemEnum(_UCSI_GET_PDOS_SOURCE_CAPABILITIES_TYPE));
// CUSTOM_TYPE(UCSI_POWER_OPERATION_MODE, ItemEnum(_UCSI_POWER_OPERATION_MODE));
// CUSTOM_TYPE(UCSI_POWER_DIRECTION, ItemEnum(_UCSI_POWER_DIRECTION));
// CUSTOM_TYPE(UCSI_CONNECTOR_PARTNER_FLAGS, ItemEnum(_UCSI_CONNECTOR_PARTNER_FLAGS));
// CUSTOM_TYPE(UCSI_CONNECTOR_PARTNER_TYPE, ItemEnum(_UCSI_CONNECTOR_PARTNER_TYPE));
// CUSTOM_TYPE(UCSI_BATTERY_CHARGING_STATUS, ItemEnum(_UCSI_BATTERY_CHARGING_STATUS));
// end_wpp

WDF_EXTERN_C_END

#endif // _UCMUCSITRACEENUMS_H_

