/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

_WdfVersionBuild_

Module Name:

    wdfpool.h

Abstract:

    This module contains pool API's

Environment:

    kernel mode only

Revision History:


--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _WDFPOOL_H_
#define _WDFPOOL_H_



#if (NTDDI_VERSION >= NTDDI_WIN2K)





#endif // (NTDDI_VERSION >= NTDDI_WIN2K)


#endif // _WDFPOOL_H_
