// Copyright (C) Microsoft Corporation. All rights reserved.
//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _MBBCXTYPES_H_
#define _MBBCXTYPES_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



DECLARE_HANDLE( MBBREQUEST );

typedef ULONG DSS_SESSION_ID;

typedef struct _MBB_DRIVER_GLOBALS
{
    ULONG Unused;
} MBB_DRIVER_GLOBALS, *PMBB_DRIVER_GLOBALS;

typedef VOID (*MBBFUNC) (VOID);
extern MBBFUNC MbbFunctions[];




WDF_EXTERN_C_END

#endif // _MBBCXTYPES_H_

