// Copyright (C) Microsoft Corporation. All rights reserved.

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _WIFICXWAKESOURCELIST_H_
#define _WIFICXWAKESOURCELIST_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START




typedef struct _WIFI_WAKE_SOURCE_LIST
{
    ULONG Size;
    void * Reserved[4];
} WIFI_WAKE_SOURCE_LIST;

inline
void
WIFI_WAKE_SOURCE_LIST_INIT(
    _Out_ WIFI_WAKE_SOURCE_LIST * List
)
{
    RtlZeroMemory(List, sizeof(*List));
    List->Size = sizeof(*List);
}

//
// WIFI Function: WifiDeviceGetWakeSourceList
//
typedef
_IRQL_requires_(PASSIVE_LEVEL)
WDFAPI
void
(NTAPI *PFN_WIFIDEVICEGETWAKESOURCELIST)(
    _In_
    PWIFI_DRIVER_GLOBALS DriverGlobals,
    _In_
    WDFDEVICE Device,
    _Inout_
    WIFI_WAKE_SOURCE_LIST* List
    );

_IRQL_requires_(PASSIVE_LEVEL)
FORCEINLINE
void
WifiDeviceGetWakeSourceList(
    _In_
    WDFDEVICE Device,
    _Inout_
    WIFI_WAKE_SOURCE_LIST* List
    )
{
    ((PFN_WIFIDEVICEGETWAKESOURCELIST) WifiFunctions[WifiDeviceGetWakeSourceListTableIndex])(WifiDriverGlobals, Device, List);
}

//
// WIFI Function: WifiWakeSourceListGetCount
//
typedef
_IRQL_requires_(PASSIVE_LEVEL)
WDFAPI
SIZE_T
(NTAPI *PFN_WIFIWAKESOURCELISTGETCOUNT)(
    _In_
    PWIFI_DRIVER_GLOBALS DriverGlobals,
    _In_
    CONST WIFI_WAKE_SOURCE_LIST* List
    );

_IRQL_requires_(PASSIVE_LEVEL)
FORCEINLINE
SIZE_T
WifiWakeSourceListGetCount(
    _In_
    CONST WIFI_WAKE_SOURCE_LIST* List
    )
{
    return ((PFN_WIFIWAKESOURCELISTGETCOUNT) WifiFunctions[WifiWakeSourceListGetCountTableIndex])(WifiDriverGlobals, List);
}

//
// WIFI Function: WifiWakeSourceListGetElement
//
typedef
_IRQL_requires_(PASSIVE_LEVEL)
WDFAPI
WIFIWAKESOURCE
(NTAPI *PFN_WIFIWAKESOURCELISTGETELEMENT)(
    _In_
    PWIFI_DRIVER_GLOBALS DriverGlobals,
    _In_
    CONST WIFI_WAKE_SOURCE_LIST* List,
    _In_
    SIZE_T Index
    );

_IRQL_requires_(PASSIVE_LEVEL)
FORCEINLINE
WIFIWAKESOURCE
WifiWakeSourceListGetElement(
    _In_
    CONST WIFI_WAKE_SOURCE_LIST* List,
    _In_
    SIZE_T Index
    )
{
    return ((PFN_WIFIWAKESOURCELISTGETELEMENT) WifiFunctions[WifiWakeSourceListGetElementTableIndex])(WifiDriverGlobals, List, Index);
}



WDF_EXTERN_C_END

#endif // _WIFICXWAKESOURCELIST_H_

