/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    AcxGlobals.h

Abstract:

    ACX global definitions.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _ACXGLOBALS_H_
#define _ACXGLOBALS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



#ifdef __cplusplus
extern "C" {
#endif

typedef struct _ACX_DRIVER_GLOBALS {
    ULONG Reserved;
} ACX_DRIVER_GLOBALS, *PACX_DRIVER_GLOBALS;




#ifdef __cplusplus
}
#endif

WDF_EXTERN_C_END

#endif // _ACXGLOBALS_H_

